replicaCount: 1

image:
  repository: my-bank/cash-service
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8084

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

env:
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=65

startupProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 3
  failureThreshold: 40

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  periodSeconds: 20

existingSecret: ""

secrets:
  CASH_DB_PASSWORD: ""
  CASH_SERVICE_SECRET: cash-service-secret

database:
  image: postgres:17-alpine
  name: cash
  user: cash_service
  schema: cash
  passwordSecretKey: CASH_DB_PASSWORD
  storage: 1Gi

config:
  management:
    tracing:
      export:
        zipkin:
          endpoint: http://zipkin:9411/api/v2/spans
  spring:
    datasource:
      url: jdbc:postgresql://{{ include "bank-common.databaseName" . }}:5432/cash
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8180/realms/my-bank
            jwk-set-uri: http://host.minikube.internal:8180/realms/my-bank/protocol/openid-connect/certs
        client:
          provider:
            keycloak:
              token-uri: http://host.minikube.internal:8180/realms/my-bank/protocol/openid-connect/token
    kafka:
      bootstrap-servers: kafka-0.kafka-headless:9092
      producer:
        acks: all
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
        properties:
          enable.idempotence: true
          spring.json.add.type.headers: false
          delivery.timeout.ms: 8000
          request.timeout.ms: 3000
          max.block.ms: 3000
  mybank:
    logging:
      logstash:
        destination: elk-logstash:5000
    clients:
      base-urls:
        accounts-service: http://accounts-service:8082
    notifications:
      topic: notifications
      partitions: 3
      replicas: 1
