plugins {
	id 'org.springframework.boot' version '4.0.7' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
	id 'org.springframework.cloud.contract' version '5.0.3' apply false
}

ext.springCloudVersion = '2025.1.2'
ext.testcontainersVersion = '1.21.3'

subprojects {
	apply plugin: 'java'
	apply plugin: 'io.spring.dependency-management'

	group = 'ru.yandex.practicum'
	version = '1.0.0-SNAPSHOT'

	java {
		toolchain {
			languageVersion = JavaLanguageVersion.of(21)
		}
	}

	repositories {
		mavenCentral()
	}

	dependencyManagement {
		imports {
			mavenBom "org.springframework.cloud:spring-cloud-dependencies:${rootProject.springCloudVersion}"
			mavenBom "org.testcontainers:testcontainers-bom:${rootProject.testcontainersVersion}"
		}
	}

	tasks.named('test') {
		useJUnitPlatform()
		//todo ubrnt remove
		environment 'TESTCONTAINERS_RYUK_DISABLED', 'true'
	}

	tasks.register('resolveDependencies') {
		doLast {
			configurations.matching { it.canBeResolved }.each { it.resolve() }
		}
	}
}
