name: my-bank

include:
  - infra/docker-compose.yml

services:
  front-service:
    build:
      context: .
      dockerfile: services/front-service/Dockerfile
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      FRONT_SERVICE_SECRET: ${FRONT_SERVICE_SECRET:-front-service-secret}
      MYBANK_CLIENTS_BASEURLS_GATEWAY: http://host.docker.internal:8081
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_TOKEN_URI: http://keycloak:8080/realms/my-bank/protocol/openid-connect/token
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_USER_INFO_URI: http://keycloak:8080/realms/my-bank/protocol/openid-connect/userinfo
      MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT: http://zipkin.127.0.0.1.nip.io:8081/api/v2/spans
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "zipkin.127.0.0.1.nip.io:host-gateway"
