spring:
  application:
    name: accounts-service
  config:
    import:
      - "classpath:bank-chassis-defaults.yml"
      - "classpath:bank-persistence-defaults.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/my_bank_app
    username: accounts_service
    password: ${ACCOUNTS_DB_PASSWORD:accounts}
  jpa:
    properties:
      hibernate:
        default_schema: accounts
  liquibase:
    default-schema: accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: accounts-service
      client:
        registration:
          notifications-service:
            provider: keycloak
            client-id: accounts-service
            client-secret: ${ACCOUNTS_SERVICE_SECRET:accounts-service-secret}
            authorization-grant-type: client_credentials
            scope: notifications:write

mybank:
  clients:
    base-urls:
      notifications-service: http://localhost:8083

resilience4j:
  circuitbreaker:
    instances:
      notifications-service:
        base-config: default

server:
  port: 8082
