spring:
  application:
    name: accounts-service
  config:
    import:
      - "classpath:bank-chassis-defaults.yml"
      - "classpath:bank-chassis-web-defaults.yml"
      - "classpath:bank-persistence-defaults.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/my_bank_app
    username: accounts_service
    password: ${ACCOUNTS_DB_PASSWORD:accounts}
  jpa:
    properties:
      hibernate:
        default_schema: accounts
  liquibase:
    default-schema: accounts
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: accounts-service
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      fail-fast: true
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        enable.idempotence: true
        spring.json.add.type.headers: false
        delivery.timeout.ms: 8000
        request.timeout.ms: 3000
        max.block.ms: 3000

server:
  port: 8082
