--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE customers (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID         NOT NULL,
    login      VARCHAR(255) NOT NULL,
    name       VARCHAR(255) NOT NULL,
    birthdate  DATE         NOT NULL,
    created_ts TIMESTAMPTZ  NOT NULL,
    updated_ts TIMESTAMPTZ  NOT NULL,
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_customers_uuid UNIQUE (uuid),
    CONSTRAINT uq_customers_login UNIQUE (login)
);
