--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE accounts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid        UUID        NOT NULL,
    number      VARCHAR(20) NOT NULL,
    customer_id BIGINT      NOT NULL,
    balance     BIGINT      NOT NULL DEFAULT 0,
    created_ts  TIMESTAMPTZ NOT NULL,
    updated_ts  TIMESTAMPTZ NOT NULL,
    version     BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_accounts_uuid UNIQUE (uuid),
    CONSTRAINT uq_accounts_number UNIQUE (number),
    CONSTRAINT fk_accounts_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT ck_accounts_balance_non_negative CHECK (balance >= 0)
);

CREATE INDEX ix_accounts_customer ON accounts (customer_id);
