--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE transactions (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID        NOT NULL,
    type       VARCHAR(16) NOT NULL,
    created_ts TIMESTAMPTZ NOT NULL,
    updated_ts TIMESTAMPTZ NOT NULL,
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_transactions_uuid UNIQUE (uuid),
    CONSTRAINT ck_transactions_type CHECK (type IN ('DEPOSIT', 'WITHDRAW', 'TRANSFER'))
);
