--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE balance_operations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid       UUID        NOT NULL,
    account_id BIGINT      NOT NULL,
    type       VARCHAR(16) NOT NULL,
    amount     BIGINT      NOT NULL,
    created_ts TIMESTAMPTZ NOT NULL,
    updated_ts TIMESTAMPTZ NOT NULL,
    version    BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_balance_operations_uuid UNIQUE (uuid),
    CONSTRAINT fk_balance_operations_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_balance_operations_type CHECK (type IN ('DEPOSIT', 'WITHDRAW')),
    CONSTRAINT ck_balance_operations_amount_positive CHECK (amount > 0)
);

CREATE INDEX ix_balance_operations_account ON balance_operations (account_id);
