--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE balance_operations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID        NOT NULL,
    transaction_id BIGINT      NOT NULL,
    account_id     BIGINT      NOT NULL,
    direction      VARCHAR(16) NOT NULL,
    amount         BIGINT      NOT NULL,
    balance_after  BIGINT      NOT NULL,
    created_ts     TIMESTAMPTZ NOT NULL,
    updated_ts     TIMESTAMPTZ NOT NULL,
    version        BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_balance_operations_uuid UNIQUE (uuid),
    CONSTRAINT uq_balance_operations_transaction_direction UNIQUE (transaction_id, direction),
    CONSTRAINT uq_balance_operations_transaction_account UNIQUE (transaction_id, account_id),
    CONSTRAINT fk_balance_operations_transaction FOREIGN KEY (transaction_id) REFERENCES transactions (id),
    CONSTRAINT fk_balance_operations_account FOREIGN KEY (account_id) REFERENCES accounts (id),
    CONSTRAINT ck_balance_operations_direction CHECK (direction IN ('DEPOSIT', 'WITHDRAW')),
    CONSTRAINT ck_balance_operations_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_balance_operations_balance_after_non_negative CHECK (balance_after >= 0)
);

CREATE INDEX ix_balance_operations_account ON balance_operations (account_id);
