--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE outbox_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID        NOT NULL,
    event_type     VARCHAR(32) NOT NULL,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    recipient      JSONB       NOT NULL,
    payload        JSONB       NOT NULL,
    status         VARCHAR(16) NOT NULL,
    locked_at      TIMESTAMPTZ,
    processed_at   TIMESTAMPTZ,
    attempts       INTEGER     NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_ts     TIMESTAMPTZ NOT NULL,
    updated_ts     TIMESTAMPTZ NOT NULL,
    version        BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_outbox_events_uuid UNIQUE (uuid),
    CONSTRAINT ck_outbox_events_status CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')),
    CONSTRAINT ck_outbox_events_attempts_non_negative CHECK (attempts >= 0)
);

CREATE INDEX ix_outbox_events_status_id ON outbox_events (status, id);
