apiVersion: v2
name: my-bank
description: My-bank microservices and their databases
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: kafka
    version: 1.0.0
    repository: "file://../kafka"
    condition: kafka.enabled
  - name: zipkin
    version: 1.0.0
    repository: "file://../zipkin"
    condition: zipkin.enabled
  - name: accounts-service
    version: 1.0.0
    repository: "file://../accounts-service"
    condition: accounts-service.enabled
  - name: notifications-service
    version: 1.0.0
    repository: "file://../notifications-service"
    condition: notifications-service.enabled
  - name: cash-service
    version: 1.0.0
    repository: "file://../cash-service"
    condition: cash-service.enabled
  - name: transfer-service
    version: 1.0.0
    repository: "file://../transfer-service"
    condition: transfer-service.enabled
