kafka:
  storage: 10Gi

accounts-service:
  replicaCount: 2
  existingSecret: my-bank-accounts
  database:
    storage: 10Gi
  config:
    logging:
      level:
        ru.yandex.practicum.mybank: INFO

notifications-service:
  existingSecret: my-bank-notifications
  database:
    storage: 5Gi
  config:
    logging:
      level:
        ru.yandex.practicum.mybank: INFO

cash-service:
  replicaCount: 2
  existingSecret: my-bank-cash
  database:
    storage: 10Gi
  config:
    logging:
      level:
        ru.yandex.practicum.mybank: INFO

transfer-service:
  replicaCount: 2
  existingSecret: my-bank-transfer
  database:
    storage: 10Gi
  config:
    logging:
      level:
        ru.yandex.practicum.mybank: INFO

prometheus:
  retention: 15d
  frontService:
    scrape: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi

elk:
  elasticsearch:
    javaOpts: "-Xms2g -Xmx2g"
    resources:
      requests:
        cpu: 500m
        memory: 3Gi
      limits:
        memory: 4Gi
  logstash:
    javaOpts: "-Xms1g -Xmx1g"
    resources:
      requests:
        cpu: 300m
        memory: 1536Mi
      limits:
        memory: 2Gi
