spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_bank_app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-bank
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/my-bank
