apiVersion: v2
name: grafana
description: Grafana dashboards and alerting for my-bank metrics
type: application
version: 1.0.0
appVersion: "13.1.4"

dependencies:
  - name: bank-common
    version: 1.0.0
    repository: "file://../bank-common"
