replicaCount: 1

image:
  repository: my-bank/notifications-service
  tag: ""
  pullPolicy: IfNotPresent

service:
  port: 8083

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

env:
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=65

startupProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 3
  failureThreshold: 40

readinessProbe:
  httpGet:
    path: /actuator/health/readiness
    port: http
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /actuator/health/liveness
    port: http
  periodSeconds: 20

existingSecret: ""

secrets:
  NOTIFICATIONS_DB_PASSWORD: ""
  NOTIFICATIONS_SERVICE_SECRET: notifications-service-secret

database:
  image: postgres:17-alpine
  name: notifications
  user: notifications_service
  schema: notifications
  passwordSecretKey: NOTIFICATIONS_DB_PASSWORD
  storage: 1Gi

config:
  management:
    tracing:
      export:
        zipkin:
          endpoint: http://zipkin:9411/api/v2/spans
  spring:
    datasource:
      url: jdbc:postgresql://{{ include "bank-common.databaseName" . }}:5432/notifications
    security:
      oauth2:
        client:
          provider:
            keycloak:
              token-uri: http://host.minikube.internal:8180/realms/my-bank/protocol/openid-connect/token
    kafka:
      bootstrap-servers: kafka-0.kafka-headless:9092
      consumer:
        group-id: notifications-service
        auto-offset-reset: earliest
        enable-auto-commit: false
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
        properties:
          spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
          spring.json.use.type.headers: false
          spring.json.value.default.type: ru.yandex.practicum.mybank.notifications.dto.NotificationEvent
      listener:
        ack-mode: RECORD
        concurrency: 3
  mybank:
    logging:
      logstash:
        destination: elk-logstash:5000
    clients:
      base-urls:
        accounts-service: http://accounts-service:8082
    notifications:
      topic: notifications
