spring:
  jackson:
    default-property-inclusion: non_null
  http:
    clients:
      connect-timeout: 2s
      read-timeout: 5s

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    correlation: "[%X{traceId:-},%X{spanId:-}] "
  level:
    ru.yandex.practicum.mybank: DEBUG
