spring:
  http:
    clients:
      read-timeout: 25s
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: front-service
            client-secret: ${FRONT_SERVICE_SECRET:front-service-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile
              - customer:read
              - customer:write
              - customer:others:read
              - cash:write
              - transfer:write
        provider:
          keycloak:
            user-name-attribute: preferred_username

mybank:
  oauth2:
    end-session-uri: http://localhost:8180/realms/my-bank/protocol/openid-connect/logout
