spring:
  reactor:
    context-propagation: auto

resilience4j:
  circuitbreaker:
    instances:
      accounts-service:
        base-config: default
      cash-service:
        base-config: default
      transfer-service:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 20s
        cancel-running-future: false
    instances:
      accounts-service:
        base-config: default
      cash-service:
        base-config: default
      transfer-service:
        base-config: default
