apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bank-common.name" . }}
  labels:
    {{- include "bank-common.labels" . | nindent 4 }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.adminUser | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ required "grafana.adminPassword is required" .Values.adminPassword | quote }}
