--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE transfer_operations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid               UUID        NOT NULL,
    transaction_uuid   UUID        NOT NULL,
    from_account_uuid  UUID,
    from_customer_uuid UUID,
    to_account_uuid    UUID,
    to_customer_uuid   UUID,
    amount             BIGINT      NOT NULL,
    status             VARCHAR(16) NOT NULL,
    failure_reason     VARCHAR(64),
    created_ts         TIMESTAMPTZ NOT NULL,
    updated_ts         TIMESTAMPTZ NOT NULL,
    version            BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_transfer_operations_uuid UNIQUE (uuid),
    CONSTRAINT uq_transfer_operations_transaction_uuid UNIQUE (transaction_uuid),
    CONSTRAINT ck_transfer_operations_status CHECK (status IN ('COMPLETED', 'FAILED')),
    CONSTRAINT ck_transfer_operations_amount_positive CHECK (amount > 0)
);
