--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE transfer_operations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid                UUID         NOT NULL,
    from_customer_login VARCHAR(255) NOT NULL,
    from_customer_uuid  UUID,
    from_account_uuid   UUID,
    to_customer_uuid    UUID,
    to_account_uuid     UUID,
    amount              BIGINT       NOT NULL,
    status              VARCHAR(16)  NOT NULL,
    failure_reason      VARCHAR(64),
    created_ts          TIMESTAMPTZ  NOT NULL,
    updated_ts          TIMESTAMPTZ  NOT NULL,
    version             BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_transfer_operations_uuid UNIQUE (uuid),
    CONSTRAINT ck_transfer_operations_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_transfer_operations_amount_positive CHECK (amount > 0)
);
