--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE cash_operations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID         NOT NULL,
    customer_login VARCHAR(255) NOT NULL,
    customer_uuid  UUID,
    account_uuid   UUID,
    type           VARCHAR(16)  NOT NULL,
    amount         BIGINT       NOT NULL,
    status         VARCHAR(16)  NOT NULL,
    failure_reason VARCHAR(64),
    created_ts     TIMESTAMPTZ  NOT NULL,
    updated_ts     TIMESTAMPTZ  NOT NULL,
    version        BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT uq_cash_operations_uuid UNIQUE (uuid),
    CONSTRAINT ck_cash_operations_type CHECK (type IN ('DEPOSIT', 'WITHDRAW')),
    CONSTRAINT ck_cash_operations_status CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_cash_operations_amount_positive CHECK (amount > 0)
);

CREATE INDEX ix_cash_operations_status_id ON cash_operations (status, id);
