--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE notifications_outbox (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid           UUID        NOT NULL,
    event_type     VARCHAR(32) NOT NULL,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    recipient_uuid UUID        NOT NULL,
    payload        JSONB       NOT NULL,
    status         VARCHAR(16) NOT NULL,
    locked_at      TIMESTAMPTZ,
    processed_at   TIMESTAMPTZ,
    attempts       INTEGER     NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_ts     TIMESTAMPTZ NOT NULL,
    updated_ts     TIMESTAMPTZ NOT NULL,
    version        BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_notifications_outbox_uuid UNIQUE (uuid),
    CONSTRAINT ck_notifications_outbox_status CHECK (status IN ('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED')),
    CONSTRAINT ck_notifications_outbox_attempts_non_negative CHECK (attempts >= 0)
);

CREATE INDEX ix_notifications_outbox_status_id ON notifications_outbox (status, id);
