plugins {
	id 'java-library'
}

dependencyManagement {
	imports {
		mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES
	}
}

dependencies {
	api project(':bank-chassis')
	api 'org.springframework.boot:spring-boot-starter-web'
	api 'org.springframework.security:spring-security-oauth2-jose'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
