image: apache/kafka:4.2.1

replicaCount: 1

clusterId: my-bank-kafka-cluster

service:
  port: 9092
  controllerPort: 9093

storage: 2Gi

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

heapOpts: "-Xms256m -Xmx512m"

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 1Gi

config:
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  transactionStateLogMinIsr: 1
  defaultReplicationFactor: 1
  minInsyncReplicas: 1

tests:
  image: apache/kafka:4.2.1
