apiVersion: v2
name: prometheus
description: Prometheus metrics collection and alerting toolkit
type: application
version: 1.0.0
appVersion: "3.14.0"

dependencies:
  - name: bank-common
    version: 1.0.0
    repository: "file://../bank-common"
