spring:
  application:
    name: notifications-service
  config:
    import:
      - "classpath:bank-chassis-defaults.yml"
      - "classpath:bank-chassis-client-defaults.yml"
      - "classpath:bank-persistence-defaults.yml"
  datasource:
    url: jdbc:postgresql://localhost:5432/my_bank_app
    username: notifications_service
    password: ${NOTIFICATIONS_DB_PASSWORD:notifications}
  jpa:
    properties:
      hibernate:
        default_schema: notifications
  liquibase:
    default-schema: notifications
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notifications-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.use.type.headers: false
        spring.json.value.default.type: ru.yandex.practicum.mybank.notifications.dto.NotificationEvent
    listener:
      ack-mode: RECORD
      concurrency: 3
      observation-enabled: true
  security:
    oauth2:
      client:
        registration:
          accounts-service:
            provider: keycloak
            client-id: notifications-service
            client-secret: ${NOTIFICATIONS_SERVICE_SECRET:notifications-service-secret}
            authorization-grant-type: client_credentials
            scope: customer:any:read

mybank:
  notifications:
    topic: notifications
  clients:
    base-urls:
      accounts-service: http://localhost:8082

resilience4j:
  circuitbreaker:
    instances:
      accounts-service:
        base-config: default

server:
  port: 8083
