spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/my_bank_app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/my-bank
          jwk-set-uri: http://keycloak:8080/realms/my-bank/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8080/realms/my-bank/protocol/openid-connect/token
