--liquibase formatted sql

--changeset ubrnt:1
CREATE TABLE notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid          UUID        NOT NULL,
    event_uuid    UUID        NOT NULL,
    customer_uuid UUID        NOT NULL,
    type          VARCHAR(32) NOT NULL,
    payload       JSONB       NOT NULL,
    message       TEXT        NOT NULL,
    created_ts    TIMESTAMPTZ NOT NULL,
    updated_ts    TIMESTAMPTZ NOT NULL,
    version       BIGINT      NOT NULL DEFAULT 0,
    CONSTRAINT uq_notifications_uuid UNIQUE (uuid),
    CONSTRAINT uq_notifications_event_uuid UNIQUE (event_uuid),
    CONSTRAINT ck_notifications_type CHECK (type IN ('MONEY_DEPOSITED', 'MONEY_WITHDRAWN', 'MONEY_SENT', 'MONEY_RECEIVED', 'PROFILE_UPDATED'))
);
